import type { JSONSchema7 } from "json-schema";
import type { WorkflowDefinition } from "../workflow/types.js";
import type { GeneratorEndpoint } from "./types.js";
import { escapeBlockComment } from "./escape.js";

/** Indent a multi-line JSON blob so it nests cleanly inside generated source. */
function indentJson(value: unknown, indent = "const "): string {
  void indent;
  return JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "  " + line))
    .join("\n");
}

/** Map a JSON-schema param entry to a Zod expression usable under Zod 3 and 4. */
function zodForParam(schema: JSONSchema7 | undefined): string {
  const type =
    typeof schema?.type === "string" ? schema.type.toLowerCase() : "";
  switch (type) {
    case "string":
      return "z.string()";
    case "number":
    case "integer":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "array":
      return "z.array(z.any())";
    case "object":
      return "z.record(z.string(), z.any())";
    default:
      return "z.any()";
  }
}

function zodShape(params: JSONSchema7): string {
  const props =
    (params.properties as Record<string, JSONSchema7> | undefined) ?? {};
  const required = new Set(
    Array.isArray(params.required) ? params.required : [],
  );
  const entries = Object.entries(props).map(([key, schema]) => {
    const base = zodForParam(schema);
    const desc = schema?.description
      ? `.describe(${JSON.stringify(schema.description)})`
      : "";
    const optional = required.has(key) ? "" : ".optional()";
    return `      ${JSON.stringify(key)}: ${base}${desc}${optional}`;
  });
  return entries.length > 0 ? `{\n${entries.join(",\n")}\n    }` : "{}";
}

/** Generate `src/tools/<name>.ts` — the workflow embedded as data + handler. */
export function generateToolFile(workflow: WorkflowDefinition): string {
  return `/**
 * Workflow tool: ${escapeBlockComment(workflow.name)}
 * ${escapeBlockComment(workflow.description)}
 *
 * Steps: ${escapeBlockComment(workflow.steps.map((s) => s.id).join(" -> "))}
 * Generated by mcp-server-generator.
 */
import { runWorkflow } from "../engine/index.js";
import type { WorkflowDefinition } from "../engine/types.js";
import type {
  EndpointInfo,
  WorkflowClient,
  WorkflowServer,
} from "../engine/executor.js";

const workflow: WorkflowDefinition = ${indentJson(workflow)};

export const tool = {
  name: ${JSON.stringify(workflow.name)},
  description: ${JSON.stringify(workflow.description)},
};

export interface ToolContext {
  client: WorkflowClient;
  server: WorkflowServer;
  endpoints: Record<string, EndpointInfo>;
}

export function createHandler(ctx: ToolContext) {
  return async (args: Record<string, unknown>) => {
    const result = await runWorkflow(workflow, args, ctx);
    return {
      content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
      ...(result.status === "error" ? { isError: true } : {}),
    };
  };
}
`;
}

/** A representative sample value for a param, used to seed generated tests. */
function sampleArgValue(schema: JSONSchema7 | undefined): unknown {
  const type =
    typeof schema?.type === "string" ? schema.type.toLowerCase() : "";
  switch (type) {
    case "number":
    case "integer":
      return 1;
    case "boolean":
      return true;
    case "array":
      return [];
    case "object":
      return {};
    case "string":
    default:
      return "test";
  }
}

/** Build a full argument object for a workflow from its param schema. */
function sampleArgs(params: JSONSchema7): Record<string, unknown> {
  const props =
    (params.properties as Record<string, JSONSchema7> | undefined) ?? {};
  const out: Record<string, unknown> = {};
  for (const [key, schema] of Object.entries(props)) {
    out[key] = sampleArgValue(schema);
  }
  return out;
}

/**
 * Generate `src/tests/setup.ts` — shared, network-free mocks so generated
 * tests exercise the real workflow engine on synthetic data.
 */
export function generateTestSetup(): string {
  return `/**
 * Shared test setup — in-memory mocks for the workflow engine.
 *
 * These let the generated tests run the real engine end-to-end with no network
 * calls and no LLM: \`request\` returns generic, shape-rich data, sampling
 * returns JSON, and elicitation always accepts.
 * Generated by mcp-server-generator.
 */
import type {
  ApiResponse,
  EndpointInfo,
  WorkflowClient,
  WorkflowServer,
} from "../engine/executor.js";
import { endpointMap } from "../endpoints.js";

/** A generic, field-rich record so downstream steps find something to read. */
function mockRecord() {
  return {
    _id: "mock-id",
    id: "mock-id",
    name: "mock",
    fname: "mock",
    username: "mockuser",
    msg: "mock message",
    text: "mock text",
    title: "mock title",
    summary: "mock summary",
    url: "https://example.com/mock",
    ts: "2020-01-01T00:00:00.000Z",
    u: { _id: "mock-user", username: "mockuser", name: "Mock User" },
  };
}

/** A permissive mock client — every request "succeeds" with generic data. */
export function createMockClient(): WorkflowClient {
  return {
    async request(): Promise<ApiResponse> {
      const record = mockRecord();
      return {
        ok: true,
        status: 200,
        data: {
          success: true,
          messages: [record],
          channels: [record],
          items: [record],
          ...record,
        },
      };
    },
  };
}

/** A mock MCP server: sampling returns JSON; elicitation always accepts. */
export function createMockServer(): WorkflowServer {
  return {
    async createMessage() {
      return {
        content: {
          type: "text",
          text: JSON.stringify({
            summary: "mock summary",
            safe: ["mock"],
            risky: [],
            flagged: ["mock"],
            approved: true,
          }),
        },
      };
    },
    async elicitInput() {
      return { action: "accept", content: { approved: true } };
    },
  };
}

/** The generated endpoint registry, typed for the engine. */
export function mockEndpoints(): Record<string, EndpointInfo> {
  return endpointMap;
}
`;
}

/** Generate `src/tests/<name>.test.ts` — a per-workflow smoke test. */
export function generateToolTest(
  workflow: WorkflowDefinition,
  moduleName: string,
): string {
  const args = JSON.stringify(sampleArgs(workflow.params), null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "  " + line))
    .join("\n");

  return `/**
 * Generated tests for the "${workflow.name}" workflow tool.
 *
 * Verifies tool metadata, endpoint wiring, and a full engine run on mock data.
 * Generated by mcp-server-generator.
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { tool, createHandler } from "../tools/${moduleName}.js";
import { endpointMap } from "../endpoints.js";
import { createMockClient, createMockServer, mockEndpoints } from "./setup.js";

const sampleArgs = ${args};
const requiredEndpoints: string[] = ${JSON.stringify(workflow.requiredEndpoints)};

describe(${JSON.stringify(workflow.name + " workflow tool")}, () => {
  it("exposes the expected tool metadata", () => {
    assert.equal(tool.name, ${JSON.stringify(workflow.name)});
    assert.ok(tool.description.length > 0, "tool has a description");
  });

  it("declares every endpoint it calls in the endpoint map", () => {
    for (const operationId of requiredEndpoints) {
      assert.ok(
        endpointMap[operationId],
        \`endpoint "\${operationId}" is missing from the endpoint map\`,
      );
    }
  });

  it("runs end-to-end on mock data and returns a well-formed MCP result", async () => {
    const handler = createHandler({
      client: createMockClient(),
      server: createMockServer(),
      endpoints: mockEndpoints(),
    });

    const result = await handler(sampleArgs);

    assert.ok(Array.isArray(result.content), "result has a content array");
    assert.equal(result.content[0].type, "text");

    const run = JSON.parse(result.content[0].text) as {
      status: string;
      completedSteps: string[];
    };
    assert.ok(
      ["success", "partial", "aborted", "error"].includes(run.status),
      \`unexpected workflow status: \${run.status}\`,
    );
    assert.ok(Array.isArray(run.completedSteps), "result reports completed steps");
  });
});
`;
}

/** Generate `src/endpoints.ts` — the operationId -> { method, path } registry. */
export function generateEndpointMap(endpoints: GeneratorEndpoint[]): string {
  const entries = endpoints
    .map(
      (ep) =>
        `  ${JSON.stringify(ep.operationId)}: { method: ${JSON.stringify(
          ep.method.toUpperCase(),
        )}, path: ${JSON.stringify(ep.path)} },`,
    )
    .join("\n");
  return `/**
 * Endpoint registry — operationId -> HTTP method + path.
 * Generated by mcp-server-generator.
 */
export const endpointMap: Record<string, { method: string; path: string }> = {
${entries}
};
`;
}

/** Generate `src/server.ts` — the entry point wiring tools to stdio transport. */
export function generateServerEntry(
  serverName: string,
  workflows: WorkflowDefinition[],
  moduleNames: string[],
): string {
  const toolImports = workflows
    .map(
      (_w, i) =>
        `import { tool as wfTool${i}, createHandler as createHandler${i} } from "./tools/${moduleNames[i]}.js";`,
    )
    .join("\n");

  const registrations = workflows
    .map(
      (w, i) =>
        `  server.registerTool(\n` +
        `    wfTool${i}.name,\n` +
        `    { description: wfTool${i}.description, inputSchema: ${zodShape(w.params)} },\n` +
        `    createHandler${i}({ client, server: workflowServer, endpoints: endpointMap }) as never,\n` +
        `  );`,
    )
    .join("\n");

  return `#!/usr/bin/env node
/**
 * ${escapeBlockComment(serverName)} — MCP server
 * Generated by mcp-server-generator. ${workflows.length} workflow tool(s).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { endpointMap } from "./endpoints.js";
import { client, initAuth } from "./rc-client.js";
import type { WorkflowServer } from "./engine/executor.js";
${toolImports}

/**
 * Adapter exposing the connected MCP client's sampling and elicitation to the
 * workflow engine. createMessage asks the client's LLM; elicitInput asks the user.
 */
function makeWorkflowServer(mcp: McpServer): WorkflowServer {
  return {
    async createMessage(message) {
      const res = await mcp.server.createMessage({
        messages: [
          { role: "user", content: { type: "text", text: message.prompt } },
        ],
        ...(message.systemPrompt ? { systemPrompt: message.systemPrompt } : {}),
        maxTokens: message.maxTokens ?? 1024,
      });
      const text =
        res.content && res.content.type === "text" ? res.content.text : "";
      return { content: { type: "text", text } };
    },
    async elicitInput(params) {
      const res = await mcp.server.elicitInput({
        message: params.message,
        requestedSchema: params.requestedSchema as never,
      });
      return { action: res.action, content: res.content };
    },
  };
}

const server = new McpServer({ name: ${JSON.stringify(serverName)}, version: "1.0.0" });
const workflowServer = makeWorkflowServer(server);

${registrations}

async function main() {
  await initAuth();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(${JSON.stringify(serverName)} + " running — ${workflows.length} workflow tool(s)");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
`;
}
