import type { JSONSchema7 } from "json-schema";
import type { WorkflowDefinition } from "../workflow/types.js";
import type { GeneratorEndpoint } from "./types.js";

/** Indent a multi-line JSON blob so it nests cleanly inside generated source. */
function indentJson(value: unknown, indent = "const "): string {
  void indent;
  return JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "  " + line))
    .join("\n");
}

/** Map a JSON-schema param entry to a Zod expression usable under Zod 3 and 4. */
function zodForParam(schema: JSONSchema7 | undefined): string {
  const type = typeof schema?.type === "string" ? schema.type.toLowerCase() : "";
  switch (type) {
    case "string":
      return "z.string()";
    case "number":
    case "integer":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "array":
      return "z.array(z.any())";
    case "object":
      return "z.record(z.string(), z.any())";
    default:
      return "z.any()";
  }
}

function zodShape(params: JSONSchema7): string {
  const props = (params.properties as Record<string, JSONSchema7> | undefined) ?? {};
  const required = new Set(Array.isArray(params.required) ? params.required : []);
  const entries = Object.entries(props).map(([key, schema]) => {
    const base = zodForParam(schema);
    const desc = schema?.description
      ? `.describe(${JSON.stringify(schema.description)})`
      : "";
    const optional = required.has(key) ? "" : ".optional()";
    return `      ${JSON.stringify(key)}: ${base}${desc}${optional}`;
  });
  return entries.length > 0 ? `{\n${entries.join(",\n")}\n    }` : "{}";
}

/** Generate `src/tools/<name>.ts` — the workflow embedded as data + handler. */
export function generateToolFile(workflow: WorkflowDefinition): string {
  return `/**
 * Workflow tool: ${workflow.name}
 * ${workflow.description}
 *
 * Steps: ${workflow.steps.map((s) => s.id).join(" -> ")}
 * Generated by mcp-server-generator.
 */
import { runWorkflow } from "../engine/index.js";
import type { WorkflowDefinition } from "../engine/types.js";
import type {
  EndpointInfo,
  WorkflowClient,
  WorkflowServer,
} from "../engine/executor.js";

const workflow: WorkflowDefinition = ${indentJson(workflow)};

export const tool = {
  name: ${JSON.stringify(workflow.name)},
  description: ${JSON.stringify(workflow.description)},
};

export interface ToolContext {
  client: WorkflowClient;
  server: WorkflowServer;
  endpoints: Record<string, EndpointInfo>;
}

export function createHandler(ctx: ToolContext) {
  return async (args: Record<string, unknown>) => {
    const result = await runWorkflow(workflow, args, ctx);
    return {
      content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
      ...(result.status === "error" ? { isError: true } : {}),
    };
  };
}
`;
}

/** Generate `src/endpoints.ts` — the operationId -> { method, path } registry. */
export function generateEndpointMap(endpoints: GeneratorEndpoint[]): string {
  const entries = endpoints
    .map(
      (ep) =>
        `  ${JSON.stringify(ep.operationId)}: { method: ${JSON.stringify(
          ep.method.toUpperCase(),
        )}, path: ${JSON.stringify(ep.path)} },`,
    )
    .join("\n");
  return `/**
 * Endpoint registry — operationId -> HTTP method + path.
 * Generated by mcp-server-generator.
 */
export const endpointMap: Record<string, { method: string; path: string }> = {
${entries}
};
`;
}

/** Generate `src/server.ts` — the entry point wiring tools to stdio transport. */
export function generateServerEntry(
  serverName: string,
  workflows: WorkflowDefinition[],
): string {
  const toolImports = workflows
    .map(
      (w, i) =>
        `import { tool as wfTool${i}, createHandler as createHandler${i} } from "./tools/${w.name}.js";`,
    )
    .join("\n");

  const registrations = workflows
    .map(
      (w, i) =>
        `  server.registerTool(\n` +
        `    wfTool${i}.name,\n` +
        `    { description: wfTool${i}.description, inputSchema: ${zodShape(w.params)} },\n` +
        `    createHandler${i}({ client, server: workflowServer, endpoints: endpointMap }) as never,\n` +
        `  );`,
    )
    .join("\n");

  return `#!/usr/bin/env node
/**
 * ${serverName} — MCP server
 * Generated by mcp-server-generator. ${workflows.length} workflow tool(s).
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { endpointMap } from "./endpoints.js";
import { client, initAuth } from "./rc-client.js";
import type { WorkflowServer } from "./engine/executor.js";
${toolImports}

/**
 * Adapter exposing the connected MCP client's sampling and elicitation to the
 * workflow engine. createMessage asks the client's LLM; elicitInput asks the user.
 */
function makeWorkflowServer(mcp: McpServer): WorkflowServer {
  return {
    async createMessage(message) {
      const res = await mcp.server.createMessage({
        messages: [
          { role: "user", content: { type: "text", text: message.prompt } },
        ],
        ...(message.systemPrompt ? { systemPrompt: message.systemPrompt } : {}),
        maxTokens: message.maxTokens ?? 1024,
      });
      const text =
        res.content && res.content.type === "text" ? res.content.text : "";
      return { content: { type: "text", text } };
    },
    async elicitInput(params) {
      const res = await mcp.server.elicitInput({
        message: params.message,
        requestedSchema: params.requestedSchema as never,
      });
      return { action: res.action, content: res.content };
    },
  };
}

const server = new McpServer({ name: ${JSON.stringify(serverName)}, version: "1.0.0" });
const workflowServer = makeWorkflowServer(server);

${registrations}

async function main() {
  await initAuth();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(${JSON.stringify(serverName)} + " running — ${workflows.length} workflow tool(s)");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
`;
}
