import type { WorkflowDefinition } from "../workflow/types.js";
import type { GeneratorEndpoint } from "./types.js";

/** Generate `src/rc-client.ts` — a Rocket.Chat HTTP client implementing WorkflowClient. */
export function generateRcClient(): string {
  return `/**
 * Rocket.Chat HTTP client. Implements the engine's WorkflowClient contract:
 *   request(method, path, { auth, body }) -> { ok, status, data }
 *
 * Auth priority:
 *   1. ROCKETCHAT_AUTH_TOKEN + ROCKETCHAT_USER_ID — used directly
 *   2. ROCKETCHAT_USER + ROCKETCHAT_PASSWORD — auto-login at startup
 *   3. neither — unconfigured (auth'd calls will fail)
 * Generated by mcp-server-generator.
 */
const config = {
  baseUrl: process.env.ROCKETCHAT_URL || "http://localhost:3000",
  authToken: process.env.ROCKETCHAT_AUTH_TOKEN || "",
  userId: process.env.ROCKETCHAT_USER_ID || "",
};

const REQUEST_TIMEOUT_MS = Number(process.env.ROCKETCHAT_REQUEST_TIMEOUT_MS) || 30000;

export interface ApiResponse {
  ok: boolean;
  status: number;
  data: unknown;
}

async function parseBody(res: Response): Promise<unknown> {
  const raw = await res.text();
  if (raw.length === 0) return null;
  const contentType = res.headers.get("content-type") || "";
  if (contentType.includes("json")) {
    try {
      return JSON.parse(raw);
    } catch {
      return raw;
    }
  }
  return raw;
}

let initialized = false;

export async function initAuth(): Promise<void> {
  if (initialized) return;
  initialized = true;

  if (config.authToken && config.userId) {
    console.error("Using pre-existing Rocket.Chat auth tokens.");
    return;
  }

  const user = process.env.ROCKETCHAT_USER || "";
  const password = process.env.ROCKETCHAT_PASSWORD || "";
  if (!user || !password) {
    console.error("No Rocket.Chat credentials set — starting unconfigured.");
    return;
  }

  try {
    const res = await fetch(config.baseUrl + "/api/v1/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ user, password }),
    });
    const data = (await parseBody(res)) as {
      data?: { authToken?: string; userId?: string };
    };
    if (res.ok && data?.data?.authToken && data.data.userId) {
      config.authToken = data.data.authToken;
      config.userId = data.data.userId;
      console.error("Authenticated as " + user);
    } else {
      console.error("Rocket.Chat login failed (HTTP " + res.status + ").");
    }
  } catch (err) {
    console.error("Could not reach Rocket.Chat for login: " + String(err));
  }
}

function buildUrl(path: string): string {
  return path.startsWith("http") ? path : config.baseUrl + path;
}

class RocketChatClient {
  async request(
    method: string,
    path: string,
    options: { auth?: boolean; body?: Record<string, unknown> } = {},
  ): Promise<ApiResponse> {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (options.auth) {
      headers["X-Auth-Token"] = config.authToken;
      headers["X-User-Id"] = config.userId;
    }

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
      const res = await fetch(buildUrl(path), {
        method,
        headers,
        ...(options.body !== undefined ? { body: JSON.stringify(options.body) } : {}),
        signal: controller.signal,
      });
      const data = await parseBody(res);
      return { ok: res.ok, status: res.status, data };
    } catch (err) {
      return {
        ok: false,
        status: 0,
        data: err instanceof Error ? err.message : String(err),
      };
    } finally {
      clearTimeout(timer);
    }
  }
}

export const client = new RocketChatClient();
`;
}

export function generatePackageJson(serverName: string): string {
  const pkg = {
    name: serverName,
    version: "1.0.0",
    type: "module",
    engines: { node: ">=20" },
    scripts: {
      start: "node --env-file-if-exists=.env --import tsx src/server.ts",
      build: "tsc",
      "start:built": "node dist/server.js",
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.27.1",
      acorn: "^8.17.0",
      zod: "^4.3.6",
    },
    devDependencies: {
      "@types/json-schema": "^7.0.15",
      "@types/node": "^22.0.0",
      tsx: "^4.21.0",
      typescript: "^5.9.3",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2022",
      module: "Node16",
      moduleResolution: "Node16",
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      types: ["node"],
    },
    include: ["src"],
  };
  return JSON.stringify(config, null, 2) + "\n";
}

export function generateGitignore(): string {
  return ["node_modules/", "dist/", ".env", ".env.*", "!.env.example", "*.log", ".DS_Store", ""].join(
    "\n",
  );
}

export function generateEnvExample(usesSampling: boolean): string {
  let env = `# Rocket.Chat connection
ROCKETCHAT_URL=http://localhost:3000

# Credentials — the server acts as this user
ROCKETCHAT_USER=your-username
ROCKETCHAT_PASSWORD=your-password

# Or token auth (takes priority over user/password)
# ROCKETCHAT_AUTH_TOKEN=
# ROCKETCHAT_USER_ID=
`;
  if (usesSampling) {
    env += `
# Sampling steps request the MCP client's LLM, so no extra key is required when
# your MCP client supports sampling.
`;
  }
  return env;
}

export function generateReadme(
  serverName: string,
  workflows: WorkflowDefinition[],
  endpoints: GeneratorEndpoint[],
): string {
  const date = new Date().toISOString().split("T")[0];
  const workflowRows = workflows
    .map((w) => {
      const features: string[] = [];
      if (w.usesSampling) features.push("AI");
      if (w.usesElicitation) features.push("Human-in-loop");
      const badge = features.length > 0 ? features.join(", ") : "Automation";
      return `| \`${w.name}\` | ${w.description} | ${w.steps.length} | ${badge} |`;
    })
    .join("\n");
  const endpointRows = endpoints
    .map(
      (ep) =>
        `| \`${ep.operationId}\` | \`${ep.method.toUpperCase()}\` | \`${ep.path}\` |`,
    )
    .join("\n");

  return `# ${serverName}

A workflow-based [MCP](https://modelcontextprotocol.io/) server for Rocket.Chat,
generated by **mcp-server-generator**. Each tool runs a multi-step workflow that
chains API calls, AI sampling, and user confirmation behind one call.

> Generated on ${date}

## Quick start

\`\`\`bash
npm install
cp .env.example .env   # fill in your Rocket.Chat credentials
npm start
\`\`\`

## Workflow tools

| Tool | Description | Steps | Features |
|------|-------------|-------|----------|
${workflowRows}

## API endpoints used

| operationId | Method | Path |
|-------------|--------|------|
${endpointRows}

## Project layout

\`\`\`
${serverName}/
├── src/
│   ├── server.ts       # entry point — wires tools to stdio transport
│   ├── rc-client.ts    # Rocket.Chat HTTP client
│   ├── endpoints.ts    # operationId -> method + path
│   ├── engine/         # vendored workflow engine
│   └── tools/          # one file per workflow
├── .env.example
├── package.json
├── tsconfig.json
└── README.md
\`\`\`

---

*Generated by mcp-server-generator.*
`;
}
